openapi: 3.1.1
info:
  title: Sample
  description: API for Sample application
  version: '1.0'
  contact:
    email: erfan.ehsany@outlook.com
servers:
  - url: http://127.0.0.1:8000
  - url: http://localhost:8000
tags:
  - name: common
    description: common web services
  - name: user
    description: user web services
security:
  - BearerAuth: []
paths:
  /api/v1/common/teapot:
    get:
      summary: Returns a teapot message
      description: Returns localized teapot text based on `lang` query parameter
      tags:
        - common
      parameters:
        - $ref: '#/components/parameters/LanguageHeader'
        - $ref: '#/components/parameters/RequestIdHeader'
      responses:
        '200':
          $ref: '#/components/responses/TeapotResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
  /api/v1/user/login:
    post:
      tags:
        - user
      parameters:
        - $ref: '#/components/parameters/LanguageHeader'
        - $ref: '#/components/parameters/RequestIdHeader'
      requestBody:
        $ref: '#/components/requestBodies/LoginRequest'
      responses:
        '200':
          $ref: '#/components/responses/LoginResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
  /api/v1/user:
    get:
      summary: Create a new user
      description: Create a new user with provided data
      tags:
        - user
      parameters:
        - $ref: '#/components/parameters/LanguageHeader'
        - $ref: '#/components/parameters/RequestIdHeader'
        - $ref: '#/components/parameters/PagePaginationQuery'
        - $ref: '#/components/parameters/PageSizePaginationQuery'
        - $ref: '#/components/parameters/FilterPaginationQuery'
      responses:
        '200':
          $ref: '#/components/responses/UsersPaginatedResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
      post:
        summary: Create a new user
        description: Create a new user with provided data
        tags:
          - user
        parameters:
          - $ref: '#/components/parameters/LanguageHeader'
          - $ref: '#/components/parameters/RequestIdHeader'
        requestBody:
          $ref: '#/components/requestBodies/CreateUserRequest'
        responses:
          '201':
            $ref: '#/components/responses/UsersDetailCreateResponse'
          '400':
            $ref: '#/components/responses/400'
          '401':
            $ref: '#/components/responses/401'
          '403':
            $ref: '#/components/responses/403'
          '404':
            $ref: '#/components/responses/404'
          '422':
            $ref: '#/components/responses/422'
  /api/v1/user/{id}:
    get:
      summary: get user detail
      description: Returns user detail
      tags:
        - user
      parameters:
        - $ref: '#/components/parameters/LanguageHeader'
        - $ref: '#/components/parameters/RequestIdHeader'
      responses:
        '200':
          $ref: '#/components/responses/UsersDetailResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
    put:
      summary: Update an existing user
      description: Update user data partially or fully
      tags:
        - user
      parameters:
        - $ref: '#/components/parameters/LanguageHeader'
        - $ref: '#/components/parameters/RequestIdHeader'
      requestBody:
        $ref: '#/components/requestBodies/UpdateUserRequest'
      responses:
        '204':
          $ref: '#/components/responses/UserUpdateResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
    delete:
      summary: Delete a user
      description: Soft-delete a user by ID
      tags:
        - user
      parameters:
        - $ref: '#/components/parameters/LanguageHeader'
        - $ref: '#/components/parameters/RequestIdHeader'
      responses:
        '204':
          $ref: '#/components/responses/UserDeleteResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    UrlDetail:
      name: id
      description: Selected Item
      in: path
      required: true
      schema:
        type: integer
        format: uint64
    LanguageHeader:
      name: Accept-Language
      description: Client Language
      in: header
      required: false
      schema:
        type: string
        enum:
          - en
          - fa
        example: fa
    RequestIdHeader:
      name: X-Request-ID
      description: Request Identifier
      in: header
      required: false
      schema:
        type: string
    PagePaginationQuery:
      name: page
      description: Page Number
      in: query
      required: false
      schema:
        type: integer
        default: 20
    PageSizePaginationQuery:
      name: size
      description: Size Of Page
      in: query
      required: false
      schema:
        type: integer
        default: 0
    FilterPaginationQuery:
      name: filters
      description: Filters
      in: query
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: object
          properties:
            field:
              type: string
            operator:
              type: string
              enum:
                - eq
                - like
                - gt
                - gte
                - lt
                - lte
            value:
              oneOf:
                - type: string
                - type: number
                - type: boolean
                - type: string
                  format: date-time
  schemas:
    LoginPayload:
      type: object
      required:
        - mobile
        - password
      properties:
        mobile:
          type: string
          example: '09120000000'
        password:
          type: string
          example: secret
    LoginResult:
      type: object
      properties:
        user_info:
          $ref: '#/components/schemas/UserInfo'
        permissions:
          type: array
          items:
            type: string
          example:
            - teapot
        token:
          type: string
          example: some token...
        expires_at:
          type: integer
          format: int64
          example: 1
    UserInfo:
      type: object
      properties:
        mobile:
          type: string
          example: '09120000000'
        email:
          type: string
          format: email
          example: example.mail.com
        national_code:
          type: string
          nullable: true
          example: null
        birthdate:
          type: string
          format: date-time
          nullable: true
          example: null
    Users:
      type: object
      properties:
        page:
          type: integer
          example: 20
        size:
          type: integer
          example: 0
        count:
          type: integer
          example: 153
        items:
          type: array
          items:
            $ref: '#/components/schemas/UserInfo'
    UserDetail:
      type: object
      properties:
        id:
          type: integer
          format: uint64
          example: 1
        mobile:
          type: string
          example: '09396168479'
        email:
          type: string
          format: email
          example: user@example.com
        national_code:
          type: string
          nullable: true
          example: '1234567890'
        birthdate:
          type: string
          format: date-time
          nullable: true
          example: '1995-01-01T00:00:00Z'
        created_at:
          type: string
          format: date-time
          example: '2024-01-01T10:00:00Z'
        updated_at:
          type: string
          format: date-time
          example: '2024-01-10T12:00:00Z'
        deleted_at:
          type: string
          format: date-time
          nullable: true
          example: null
        permissions:
          type: array
          items:
            type: string
    CreateUserPayload:
      type: object
      required:
        - mobile
        - email
        - password
      properties:
        mobile:
          type: string
          example: '09121234567'
          description: User mobile number (required)
        email:
          type: string
          format: email
          example: user@example.com
          description: User email (required)
        password:
          type: string
          format: password
          description: User password (required)
        national_code:
          type: string
          nullable: true
          example: '1234567890'
          description: User national code (optional)
        birthdate:
          type: string
          format: date-time
          nullable: true
          example: '1995-01-01T00:00:00Z'
          description: User birthdate (optional)
    UpdateUserPayload:
      type: object
      properties:
        email:
          type: string
          format: email
          nullable: true
          example: user@example.com
          description: User email (optional)
        password:
          type: string
          format: password
          nullable: true
          description: User password (optional)
        national_code:
          type: string
          nullable: true
          example: '1234567890'
          description: User national code (optional)
        birthdate:
          type: string
          format: date-time
          nullable: true
          example: '1995-01-01T00:00:00Z'
          description: User birthdate (optional)
    BaseResponse:
      type: object
      properties:
        result:
          nullable: true
        error:
          nullable: true
          type: string
        success:
          type: boolean
        code:
          type: integer
          format: int32
  requestBodies:
    CreateUserRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateUserPayload'
    LoginRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginPayload'
    UpdateUserRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateUserPayload'
  responses:
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseResponse'
          example:
            result: null
            error: Bad request
            success: false
            code: 400
    '401':
      description: Invalid Or Expired Token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseResponse'
          example:
            result: null
            error: invalid or expired token
            success: false
            code: 401
    '403':
      description: Permission Denied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseResponse'
          example:
            result: null
            error: permission denied
            success: false
            code: 403
    '404':
      description: Entity Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseResponse'
          example:
            result: null
            error: entity not found
            success: false
            code: 404
    '422':
      description: Unprocessable Input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseResponse'
          example:
            result: null
            error: unprocessable input
            success: false
            code: 422
    LoginResponse:
      description: User Login Response
      content:
        application/json:
          schema:
            LoginResponse:
              type: object
              properties:
                code:
                  type: integer
                  example: 200
                error:
                  type: string
                  nullable: true
                  example: null
                result:
                  $ref: '#/components/schemas/LoginResult'
                success:
                  type: boolean
                  example: true
    TeapotResponse:
      description: Success
      content:
        text/plain:
          schema:
            type: string
    UserDeleteResponse:
      description: Updated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseResponse'
          example:
            result: null
            error: No content
            success: false
            code: 204
    UserUpdateResponse:
      description: Updated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseResponse'
          example:
            result: null
            error: No content
            success: false
            code: 204
    UsersDetailCreateResponse:
      description: User List
      content:
        application/json:
          schema:
            UsersDetailCreateResponse:
              type: object
              properties:
                result:
                  $ref: '#/components/schemas/UserDetail'
                error:
                  nullable: true
                  example: null
                success:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 201
    UsersDetailResponse:
      description: User Detail
      content:
        application/json:
          schema:
            UsersDetailCreateResponse:
              type: object
              properties:
                result:
                  $ref: '#/components/schemas/UserDetail'
                error:
                  nullable: true
                  example: null
                success:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 200
    UsersPaginatedResponse:
      description: User List
      content:
        application/json:
          schema:
            UsersPaginatedResponse:
              type: object
              properties:
                result:
                  $ref: '#/components/schemas/Users'
                error:
                  nullable: true
                  example: null
                success:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 200
